### ISSUE TITLE
Can't run gulp due to error with is-svg

### ISSUE THREAD

**Issue by applesapples1** [hew/sage-lost-stylus#6]
Hi there, I've upgraded all the node modules and done everything I can think of, but can't get past this error. Is there any advice anyone can give me as to how to resolve this? Thank you!

node_modules/is-svg/index.js:8
		var charCode = isBuf ? buf[i] : buf.charCodeAt(i);
		                                   ^

TypeError: Cannot read property 'charCodeAt' of undefined
    at isBinary (/Users/kate/Sites/heigaaudiovisual.com/wp-content/themes/sage-lost-stylus-master/node_modules/is-svg/index.js:8:38)
    at module.exports (/Users/kate/Sites/heigaaudiovisual.com/wp-content/themes/sage-lost-stylus-master/node_modules/is-svg/index.js:19:10)
    at buf (/Users/kate/Sites/heigaaudiovisual.com/wp-content/themes/sage-lost-stylus-master/node_modules/imagemin-svgo/index.js:8:7)
    at Imagemin.use (/Users/kate/Sites/heigaaudiovisual.com/wp-content/themes/sage-lost-stylus-master/node_modules/gulp-imagemin/node_modules/imagemin/index.js:63:51)
    at DestroyableTransform.through.obj.percent (/Users/kate/Sites/heigaaudiovisual.com/wp-content/themes/sage-lost-stylus-master/node_modules/gulp-imagemin/index.js:47:5)
    at DestroyableTransform._transform (/Users/kate/Sites/heigaaudiovisual.com/wp-content/themes/sage-lost-stylus-master/node_modules/through2-concurrent/through2-concurrent.js:30:15)
    at DestroyableTransform.Transform._read (/Users/kate/Sites/heigaaudiovisual.com/wp-content/themes/sage-lost-stylus-master/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/kate/Sites/heigaaudiovisual.com/wp-content/themes/sage-lost-stylus-master/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/kate/Sites/heigaaudiovisual.com/wp-content/themes/sage-lost-stylus-master/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/kate/Sites/heigaaudiovisual.com/wp-content/themes/sage-lost-stylus-master/node_modules/readable-stream/lib/_stream_writable.js:395:5)

**Comment by hew** [comment]
Hey just a quick heads up (from the Readme)

![image](https://user-images.githubusercontent.com/3103241/28983504-ef976a0c-790e-11e7-9189-c78bf7ac50aa.png)
